// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEwbJjxVYFON2s3CYSpCLH-LKprtfPN4',
    appId: '1:557373426163:web:63f87f952b1222592c6a86',
    messagingSenderId: '557373426163',
    projectId: 'rumi-skripsi',
    authDomain: 'rumi-skripsi.firebaseapp.com',
    storageBucket: 'rumi-skripsi.firebasestorage.app',
    measurementId: 'G-GLTTSME94E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsRVhdqTduwxpi6u-vjwx1u9uwUf6MbI',
    appId: '1:557373426163:android:9f19da1c4cb37f042c6a86',
    messagingSenderId: '557373426163',
    projectId: 'rumi-skripsi',
    storageBucket: 'rumi-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU5TQy19A40Q-0EUc5Az-J43AP05NJ-tY',
    appId: '1:557373426163:ios:6de5cf5d24d4f8e72c6a86',
    messagingSenderId: '557373426163',
    projectId: 'rumi-skripsi',
    storageBucket: 'rumi-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.rumi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU5TQy19A40Q-0EUc5Az-J43AP05NJ-tY',
    appId: '1:557373426163:ios:6de5cf5d24d4f8e72c6a86',
    messagingSenderId: '557373426163',
    projectId: 'rumi-skripsi',
    storageBucket: 'rumi-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.rumi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUEwbJjxVYFON2s3CYSpCLH-LKprtfPN4',
    appId: '1:557373426163:web:9d79a62f6f938c412c6a86',
    messagingSenderId: '557373426163',
    projectId: 'rumi-skripsi',
    authDomain: 'rumi-skripsi.firebaseapp.com',
    storageBucket: 'rumi-skripsi.firebasestorage.app',
    measurementId: 'G-TP4Z1DBFX2',
  );
}
